####################################################
# Application
####################################################

spring.application.name=servesmart

####################################################
# Server
####################################################

server.port=8080

####################################################
# Database
####################################################

spring.datasource.url=jdbc:mysql://localhost:3306/servesmart
spring.datasource.username=root
spring.datasource.password=

####################################################
# Hibernate
####################################################

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

####################################################
# Flyway
####################################################

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

####################################################
# Logging
####################################################

logging.level.org.springframework=INFO
logging.level.com.servesmart=DEBUG